default:
  tags:
    - my-gitlab-runner

stages:
  - plan
  - apply

before_script:
  - echo $SERVICE_ACCOUNT_JSON | base64 -d > $CI_PROJECT_DIR/service-account.json

.plan_template:
  stage: plan
  image: cr.yandex/crprles4pfjpj44kv3fh/terraform-runner:1.0.0
  script:
    - cd $TF_DIR
    - tfswitch
    - ./terraform init
    - ./terraform validate
    - ./terraform plan


.apply_template:
  stage: apply
  image: cr.yandex/crprles4pfjpj44kv3fh/terraform-runner:1.0.0
  script:
    - cd $TF_DIR
    - tfswitch
    - ./terraform init
    - ./terraform validate
    - ./terraform apply -auto-approve

include:
  - local: 'iam/.gitlab-ci.yml'
  - local: 'msk/.gitlab-ci.yml'
  - local: 'vpc/.gitlab-ci.yml'
